# Generated by Django 3.0.8 on 2020-08-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='productCode',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='productCode',
        ),
    ]
