# Generated by Django 3.0.8 on 2020-10-13 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0002_auto_20200816_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comfirm_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.CharField(default=False, max_length=25),
        ),
    ]
