# Generated by Django 3.0.8 on 2020-10-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0003_auto_20201013_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageOne',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageTwo',
            field=models.TextField(blank=True),
        ),
    ]
