# Generated by Django 3.0.8 on 2020-10-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0004_auto_20201013_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating_Value',
            field=models.IntegerField(default=0),
        ),
    ]
