# Generated by Django 3.0.8 on 2020-10-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0005_auto_20201017_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='onlineshopApp.Product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='productCode',
            field=models.IntegerField(default=0),
        ),
    ]
