# Generated by Django 3.0.8 on 2020-10-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0008_auto_20201018_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product_id',
        ),
    ]
