# Generated by Django 3.0.8 on 2020-10-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopApp', '0011_auto_20201018_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_Number',
            field=models.CharField(max_length=40),
        ),
    ]
